const RESPONSE_CODES_CATALOG = {
  OK: 200,
  ERROR: 500,
};

const RESPONSE_MESSAGE_CATALOG = {
  OK: 'CORRECT OPERATION',
  ERROR: 'INTERNAL SERVER ERROR',
};

export { RESPONSE_CODES_CATALOG, RESPONSE_MESSAGE_CATALOG };
